# Generated by Django 5.0.4 on 2024-04-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
